### ISSUE TITLE
Add 27 Supervised learning: Out-of-core learning notebook

### ISSUE THREAD

**Issue by amueller** [amueller/scipy-2016-sklearn#15]

**Comment by rasbt** [comment]
Just see that we already have that

in old-07.1 Case Study - Large Scale Text Classification.ipynb

I can pimp it up a little and make it into Nb 28, what do you think? 
Also, I think we need to load the IMDb for that. Shall we then stick to the SMS classification in Nb 14 since it would be boring to use the IMDb for both?

**Comment by amueller** [comment]
Is it boring to use the same data set twice? I find introducing too many data sets a bit confusing. But I don't mind much either way.
